# Render Blueprint for Rotary Club Portal
# This file defines the infrastructure for deploying on Render

services:
  # Backend API Server
  - type: web
    name: rotary-club-api
    env: node
    region: singapore
    plan: free  # Change to 'starter' or higher for production
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard (secret)
      - key: JWT_ACCESS_SECRET
        sync: false  # Set this in Render dashboard (secret)
      - key: JWT_REFRESH_SECRET
        sync: false  # Set this in Render dashboard (secret)
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: COOKIE_DOMAIN
        sync: false  # Set to your domain
      - key: COOKIE_SECURE
        value: true
      - key: CLIENT_URL
        sync: false  # Set to your frontend URL
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 5242880
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: rotary-club-frontend
    env: static
    region: singapore
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false  # Set to your backend API URL
      - key: VITE_SOCKET_URL
        sync: false  # Set to your backend URL
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
    autoDeploy: true
